package-lock.json, package.json, src/Components/Auth/Authed.css, src/Components/Auth/Login.jsx, src/Components/Auth/Signup.jsx
display alert with data -- to be changed to send to backend (task: #1 #2)
=> login signup UI with validation

src/App.js, src/Components/Layout/ChatWindow/ChatWindow.jsx, src/Components/Layout/ChatWindow/ChatWindow.module.css, src/Components/Views/HomePage/HomePage.jsx
=> ChatWindow implemented - button styling pending

src/App.js, src/Components/StaticElements/Message/Message.jsx, src/Components/StaticElements/Message/Message.module.css, src/Components/Views/HomePage/HomePage.jsx
=> Message static implemented

src/App.js, src/Components/Layout/ChatList/ChatList.jsx, src/Components/Layout/ChatList/ChatList.module.css, src/Components/StaticElements/SubHeader/SubHeader.jsx, src/Components/StaticElements/SubHeader/SubHeader.module.css, src/Components/Views/HomePage/HomePage.jsx
=> ChatList static implemented

src/Components/ActiveElements/SubmitMessage/SubmitMessage.jsx, src/Components/ActiveElements/SubmitMessage/SubmitMessage.module.css
=> MsgSubmit Component static Implemented

src/App.js, src/Components/Auth/Signup.jsx, src/Components/Views/BeforeAuthTabs.jsx, src/Components/Views/HomePage/HomePage.jsx, src/index.js
please note nav moved to homepage not related to before auth #28
=> added welcome page + routing

src/App.js
@ograch91 Notice need way to get auth to the navbar state to enable or disable rendering per logged in or out
=> Navbar reinstatment App with auth conditional

src/Components/Layout/NewChat/NewChatDialog.jsx
=> start new chat (select user/s)

src/Components/Layout/ChatList/ChatList.jsx
=> new chat modal and button

src/CustomHooks/UseApi.js
=> Api controller custom hook to be tested

src/App.js, src/Components/Layout/Navbar/Navbar.jsx, src/Components/Views/BeforeAuthTabs.jsx, src/Context/NavigationStateContext.js, src/index.js
=> Auth Testing component Navigation implemented

src/Components/Layout/Navbar/Navbar.jsx, src/Components/Layout/Navbar/Navbar.module.css
=> NavBar Routing Implemented

src/App.js
#57  Basic Secure Routing on client implemented
=> Client Secured Routes Implemented

src/Components/ActiveElements/SearchField/SearchField.jsx, src/Components/ActiveElements/SearchField/SearchField.module.css, src/Components/Layout/ChatList/ChatList.jsx, src/Components/Layout/ChatList/ChatList.module.css
#38 basic searchfield implemented 
results panel or debounce results pending
=> Searchfield basic implemented -pending debounce or results field

src/App.js
=> clientside secured route implemented on /setting

src/Components/Layout/ContentWrapper/ContentWrapper.module.css, src/Components/Views/ProfilePage/ProfilePage.jsx
=> Profile Page adjusted

src/Hooks/ApiWrapper/ApiWrapper.jsx
additional wrapper implemented
=> ApiHook Wrapper Component

src/Components/Layout/ChatWindow/ChatWindow.jsx, src/Components/Layout/ChatWindow/ChatWindow.module.css, src/Components/StaticElements/SubHeader/SubHeader.jsx, src/Components/StaticElements/SubHeader/SubHeader.module.css
=> Chatwindow Header Change implemented

src/Components/Layout/ChatList/ChatList.jsx, src/Components/Layout/ChatList/ChatList.module.css, src/Components/Layout/ChatWindow/ChatWindow.jsx, src/Components/StaticElements/Message/Message.jsx, src/Components/StaticElements/Message/Message.module.css, src/Components/StaticElements/SubHeader/SubHeader.jsx
=> Img switched to ChatList

src/Components/Layout/ChatWindow/ChatWindow.jsx, src/Components/StaticElements/SubHeader/SubHeader.jsx, src/Components/StaticElements/SubHeader/SubHeader.module.css
=> Chatwindow Func header implementation for Modal done

src/Components/ActiveElements/SearchField/SearchField.jsx
#38  pending implement logic for userlist db
=> searchfield debounce implemented

src/Components/Layout/Navbar/Navbar.jsx, src/Components/Modal/Modal.css, src/Components/Modal/Modal.jsx
#49  pending integration to component
=> modal component #49

src/Components/APILoaded/ProfileDetailsLoader.jsx, src/Components/Layout/Navbar/Navbar.jsx, src/Components/Modal/Modal.jsx, src/Components/Modal/Modal.module.css, src/Components/Profile/ProfileDetails.jsx
=> Image Modal integrated

src/Components/Auth/Login.jsx, src/Components/Auth/Signup.jsx
=> FIXED signup/update

src/Components/Layout/ChatWindow/ChatWindow.jsx
#51 pending backend adjustment for information then front data extraction
=> chatwindow linked to Db pending adjust backend filtering on controller

src/Components/Layout/ChatWindow/ChatWindow.jsx, src/Components/Layout/ChatWindow/ChatWindow.module.css, src/Components/StaticElements/Message/Message.jsx, src/Components/StaticElements/Message/Message.module.css, src/Components/StaticElements/SubHeader/SubHeader.module.css
=> ChatWindow connected Db client side

src/Components/Layout/ChatList/ChatList.jsx, src/Components/Layout/ChatWindow/ChatWindow.jsx, src/Components/Views/HomePage/HomePage.jsx, src/Context/CurrentChatContext.js
#93  Pending function implementation ,userDB chatId addition to user collection, date extraction from messages
=> Chatlist chat window connectivity pending - context implemented

src/Components/Layout/ChatList/ChatList.jsx
- pending chatid prop addition in usersDB collection
=> Chatlist connectivity to Chatwindow implemented 

src/Components/ActiveElements/SubmitMessage/SubmitMessage.jsx, src/Components/ActiveElements/SubmitMessage/SubmitMessage.module.css
#96 implenmented 
pending autharisation fixup on back
=> Message Submission implemented - pending auth fixup

src/Components/ActiveElements/SubmitMessage/SubmitMessage.jsx
=> Submit component to db implemented

src/Components/Layout/ChatList/ChatList.jsx, src/Components/Layout/ChatWindow/ChatWindow.jsx
=> ChatWindow ChatList Axios auth implemented

src/Components/ActiveElements/SubmitMessage/SubmitMessage.jsx
=> Disable feature implemented on button

src/Components/Layout/Navbar/Navbar.jsx, src/Components/Layout/Navbar/Navbar.module.css
=> NavBar Hover pending further work

src/Components/Layout/ChatList/ChatList.jsx
=> db data console access testing

src/Components/Layout/ChatWindow/ChatWindow.jsx
=> ChatWindow Db Accesibility text

src/Components/ActiveElements/SubmitMessage/SubmitMessage.jsx, src/Context/CurrentChatContext.js
added disabled functionality if field empty
=> User message submit component

src/Components/Layout/ChatList/ChatList.jsx, src/Components/Layout/ChatWindow/ChatWindow.jsx, src/Components/Views/HomePage/HomePage.jsx, src/Context/StarterPackChatsContext.js, src/Context/StarterPackMessagesPerChatContext.js, src/Context/StarterPackOtherUsersContext.js
#133 Pending how to await context useeffect on children component to access data on render
=> Context written -pending context sending data to children on render

src/Components/Layout/ChatList/ChatList.jsx, src/Components/Layout/ChatWindow/ChatWindow.jsx, src/Context/CurrentChatContext.js, src/Context/MainDataContext.js
=> Chat connectivity

src/Components/Layout/ChatList/ChatList.jsx, src/Components/Layout/ChatWindow/ChatWindow.jsx, src/Components/StaticElements/Message/Message.jsx, src/Components/StaticElements/Message/Message.module.css
#93 
pending chatlist full list rendering
pending diffrenciate user,otheruser chatwindow
pending submit connectivity
=> ChatWindow connected to chatlist

src/Components/ActiveElements/SubmitMessage/SubmitMessage.jsx, src/Components/Layout/ChatList/ChatList.jsx, src/Components/Layout/ChatWindow/ChatWindow.jsx, src/Components/Layout/ChatWindow/ChatWindow.module.css, src/Components/StaticElements/SubHeader/SubHeader.jsx, src/Components/StaticElements/SubHeader/SubHeader.module.css, src/Context/CurrentChatContext.js, src/Context/MainDataContext.js
#93 
Chat working only on oren for now
-pending realtime updating,chat updates only on page refresh
-pending switch to different chat, currently map goes on all chats and only renders first in list
=> chat working only on oren for now, chat updates only on page refresh

src/Components/Layout/Navbar/Navbar.jsx, src/Components/Layout/Navbar/Navbar.module.css
=> NavBar cleanup pending more testing

src/Components/Layout/Navbar/Navbar.jsx, src/Components/Layout/Navbar/Navbar.module.css
=> NavBar implemented on hover
